# Generated by Django 5.0 on 2024-04-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.CharField(max_length=1000)),
                ('project_id', models.CharField(max_length=1000)),
                ('status', models.CharField(default='Not viewd yet', max_length=1000)),
            ],
        ),
    ]
