# Generated by Django 5.0 on 2024-02-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_name', models.CharField(max_length=100)),
                ('user_name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('birthplace', models.TextField()),
                ('DOB', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='profilepic')),
            ],
        ),
    ]
