# Generated by Django 5.0 on 2024-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_freelancer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('user_name', models.TextField()),
                ('password', models.TextField(default=0)),
                ('CEO', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('headquarter', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('comany_certificate', models.FileField(default=None, upload_to='')),
                ('company_contarct', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='freelancer_contarct',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
