# Generated by Django 5.0 on 2024-03-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_client_freelancer_freelancer_contarct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='freelancer_contarct',
        ),
    ]
