# Generated by Django 5.0 on 2024-03-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_freelancer_freelancer_contarct'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='freelancer_contarct',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
