# Generated by Django 5.0 on 2024-03-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_post',
            name='payment_method',
        ),
    ]
