# Generated by Django 5.0 on 2024-03-31 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_client_user_remove_freelancer_user'),
        ('project_management', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_post',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client'),
        ),
    ]
