# Generated by Django 5.0 on 2024-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_alter_project_post_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_post',
            name='discription_image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project_post',
            name='discription_video',
            field=models.FileField(default=None, upload_to='video/%y'),
        ),
    ]
