# Generated by Django 5.0 on 2024-04-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_alter_project_post_discription_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_post',
            name='discription_image',
        ),
        migrations.RemoveField(
            model_name='project_post',
            name='discription_video',
        ),
    ]
